WIDTH_MAIN_WINDOW = 1000
HEIGHT_MAIN_WINDOW = 700

WIDTH_IMAGE_FRAME = int(WIDTH_MAIN_WINDOW / 5 * 2)
WIDTH_FILTER_FRAME = WIDTH_IMAGE_FRAME * 2
WIDTH_FILTER_LISTBOX = int(WIDTH_FILTER_FRAME / 4)
WIDTH_FILTER_CONTROL_FRAME = int(WIDTH_FILTER_FRAME / 4)
WIDTH_FILTER_SLIDER_FRAME = WIDTH_FILTER_FRAME - WIDTH_FILTER_LISTBOX - WIDTH_FILTER_CONTROL_FRAME
WIDTH_SEQUENCE_FRAME = WIDTH_MAIN_WINDOW - WIDTH_FILTER_FRAME

HEIGHT_IMAGE_FRAME = int(WIDTH_IMAGE_FRAME / 4 * 3)
HEIGHT_FILTER_FRAME = HEIGHT_MAIN_WINDOW - HEIGHT_IMAGE_FRAME

PADX = 10
PADY = 10

FONT_POINTS_2_PIXELS = 16.2

SLIDER_LENGTH = 200
